version: "3.8"
services:
  messaging:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./messaging/data:/var/lib/rabbitmq
      - ./messaging/logs:/var/logs/rabbitmq
    deploy:
      resources:
        limits:
          cpus: '5.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
  postresql:
    container_name: "database-engine"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mailing
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '5.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5055:80"
  vault:
    image: vault
    container_name: vault
    restart: always
    deploy:
      resources:
        limits:
          cpus: '5.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    volumes:
      - ./vault/logs:/vault/logs
      - ./vault/file:/vault/file
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
    cap_add:
        - IPC_LOCK
    ports:
        - "8204:8200"
        - "8205:8201"
    environment:
        VAULT_DEV_ROOT_TOKEN_ID: 'my-token-id'
        VAULT_TOKEN: 'my-token-id'
        VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
        VAULT_LOG_LEVEL: 'trace'
        VAULT_ADDR: 'http://127.0.0.1:8200'
    healthcheck:
        retries: 5
    entrypoint: vault server -config=/vault/config/vault.hcl
volumes:
  db:
    driver: local